Backport Windows and macOS build improvements & arm64 macOS support (#770)
* Backport Windows and macOS build improvements & arm64 macOS support

* fix ubuntu build

* macOS: remove DeSmuME dylib

* Remove VERSION file

* Windows: add SDL2 back in

* readd themes

* more things, for testing disable macos themes

* macOS: Add themes back

* macOS debugging

* more macOS debugging; correct data dirs

* macOS try load theme

* Bump ssb-debugger for now

* roll back theme mechanism

* add symbols module to hiddenimports

* Bump ssb-debugger for now

* Harfbuzz workaround

* macOS: Fix path for main files

* macOS: don't pull armips twice

---------

Co-authored-by: tech-ticks <techticksdev@gmail.com>

diff --git a/.github/workflows/build-test-publish.yml b/.github/workflows/build-test-publish.yml
--- a/.github/workflows/build-test-publish.yml
+++ b/.github/workflows/build-test-publish.yml
@@ -6,7 +6,6 @@ on:
   push:
     branches:
       - master
-      - l10n_master
       - release
       - version/*
   pull_request:
@@ -49,7 +48,7 @@ jobs:
         python -m pip install --upgrade pip
         pip install -r requirements.txt ruff
     - name: Lint with ruff
-      run: ruff check --output-format=github .
+      run: ruff check --output-format=github skytemple
 
   code-formatting:
     runs-on: ubuntu-latest
@@ -65,8 +64,8 @@ jobs:
           python -m pip install --upgrade pip
           pip install ruff
       - name: Check with ruff
-        run: ruff format --check .
-        
+        run: ruff format --check skytemple
+
   build:
     runs-on: ubuntu-latest
     name: Build the Python wheel
@@ -84,11 +83,10 @@ jobs:
       - name: Build localization MO files
         run: |
           installer/generate-mo.sh
-      - name: Build Python wheels
-        uses: RalfG/python-wheels-manylinux-build@v0.5.0-manylinux2014_x86_64
-        with:
-          python-versions: 'cp39-cp39 cp310-cp310 cp311-cp311 cp312-cp312'
-          system-packages: 'gettext'
+      - name: Build wheels
+        run: |
+          python3 -m pip install --upgrade pip build
+          python3 -m build
       - name: Upload wheels
         uses: actions/upload-artifact@v4
         with:
@@ -100,6 +98,7 @@ jobs:
       - build
       - package-windows
       - package-mac
+      - package-mac-arm64
     runs-on: ubuntu-latest
     name: Deploy wheels to PyPI
     steps:
@@ -128,6 +127,7 @@ jobs:
       - build
       - package-windows
       - package-mac
+      - package-mac-arm64
     concurrency:
       group: "${{ github.workflow }}-${{ github.ref }}"
     steps:
@@ -153,6 +153,12 @@ jobs:
         with:
           path: ${{ github.workspace }}/artifacts/mac_x86
           name: skytemple-mac-dmg-x86_64
+      - name: Download MacOS ARM
+        id: artifact_macos_arm64
+        uses: actions/download-artifact@v4
+        with:
+          path: ${{ github.workspace }}/artifacts/mac_arm64
+          name: skytemple-mac-dmg-arm64
       - name: Copy over distributions
         run: |
           # Replace / in PR refs (123/merge -> 123-merge)
@@ -161,11 +167,13 @@ jobs:
           PATH_WHEEL=$(eval echo "${{ steps.artifact_wheel.outputs.download-path }}/*.whl")
           PATH_WIN=$(eval echo "${{ steps.artifact_windows.outputs.download-path }}/*.exe")
           PATH_MACOS=$(eval echo "${{ steps.artifact_macos_x86.outputs.download-path }}/*.dmg")
+          PATH_MACOS_ARM=$(eval echo "${{ steps.artifact_macos_arm64.outputs.download-path }}/*.dmg")
           
-          mkdir -p /mnt/dist/randomizer
+          mkdir -p /mnt/dist/skytemple
           cp -f "$PATH_WHEEL" "/mnt/dist/skytemple/skytemple-$REF.whl"
           cp -f "$PATH_WIN" "/mnt/dist/skytemple/skytemple-$REF.exe"
           cp -f "$PATH_MACOS" "/mnt/dist/skytemple/skytemple-x86-$REF.dmg"
+          cp -f "$PATH_MACOS_ARM" "/mnt/dist/skytemple/skytemple-arm64-$REF.dmg"
   deploy-to-skytemple-dist:
     if: startsWith(github.ref, 'refs/tags/')
     runs-on: [self-hosted, skytemple-dist]
@@ -174,6 +182,7 @@ jobs:
       - build
       - package-windows
       - package-mac
+      - package-mac-arm64
     steps:
       - name: Clear
         run: |
@@ -191,13 +200,21 @@ jobs:
         with:
           path: ${{ github.workspace }}/artifacts/mac_x86
           name: skytemple-mac-dmg-x86_64
+      - name: Download MacOS ARM
+        id: artifact_macos_arm64
+        uses: actions/download-artifact@v4
+        with:
+          path: ${{ github.workspace }}/artifacts/mac_arm64
+          name: skytemple-mac-dmg-arm64
       - name: Copy over distributions
         run: |
           PATH_WIN=$(eval echo "${{ steps.artifact_windows.outputs.download-path }}/*.exe")
           PATH_MACOS=$(eval echo "${{ steps.artifact_macos_x86.outputs.download-path }}/*.dmg")
+          PATH_MACOS_ARM=$(eval echo "${{ steps.artifact_macos_arm64.outputs.download-path }}/*.dmg")
           
           dist.py "$PATH_WIN" "skytemple/$GITHUB_REF_NAME/skytemple-$GITHUB_REF_NAME-win-install.exe"
           dist.py "$PATH_MACOS" "skytemple/$GITHUB_REF_NAME/skytemple-$GITHUB_REF_NAME-mac-install-x86-64.dmg"
+          dist.py "$PATH_MACOS_ARM" "skytemple/$GITHUB_REF_NAME/skytemple-$GITHUB_REF_NAME-mac-install-arm64.dmg"
   package-windows:
     # This is partly based on https://github.com/wingtk/gvsbuild/blob/main/.github/workflows/ci.yml
     runs-on: windows-2022
@@ -270,38 +287,41 @@ jobs:
         run: |
           $ErrorActionPreference = "Stop"
 
+          $env:pathext = $env:pathext + ";.PY"
           $env:path = "C:\gtk-build\gtk\x64\release\bin;" + $env:path
           $env:LIB = "C:\gtk-build\gtk\x64\release\lib;" + $env:LIB
           $env:INCLUDE = "C:\gtk-build\gtk\x64\release\include;C:\gtk-build\gtk\x64\release\include\cairo;C:\gtk-build\gtk\x64\release\include\glib-2.0;C:\gtk-build\gtk\x64\release\include\gobject-introspection-1.0;C:\gtk-build\gtk\x64\release\lib\glib-2.0\include;" + $env:INCLUDE
 
-          cd installer
+          # Install PyGObject and pycairo
+          pip install --force-reinstall (Resolve-Path C:\gtk-build\build\x64\release\pygobject\dist\PyGObject*.whl)
+          pip install --force-reinstall (Resolve-Path C:\gtk-build\build\x64\release\pycairo\dist\pycairo*.whl)
           
-          pip debug --verbose  # print compatible tags etc. for debugging purposes
+          # Check GObject availability
+          python -c 'import gi; gi.require_version("Gtk", "3.0"); from gi.repository import GObject, Gio, GLib, Gtk, Gdk'
+          if ($LASTEXITCODE) { exit $LASTEXITCODE }
+
+          cd installer
 
           # Package
           .\build-windows.ps1 $PACKAGE_VERSION
+          if ($LASTEXITCODE) { exit $LASTEXITCODE }
 
-          
           if(!(Test-Path ".\dist\skytemple\skytemple.exe")){
-              return 1
+              exit 1
           }
-          
-          # Install latest skytemple-rust
-          if ($env:IS_DEV_BUILD) {
-              bash .\install-skytemple-rust.sh
-          }
+
       - name: Create installer
         uses: joncloud/makensis-action@v4.1
         with:
           script-file: "installer/skytemple.nsi"
-          arguments: "/DPRODUCT_VERSION=${{ env.PACKAGE_VERSION }}"
+          arguments: "/DPRODUCT_VERSION=${{ env.PACKAGE_VERSION }} /DINST_LIST=install_list.nsh /DUNINST_LIST=uninstall_list.nsh"
 
       - name: Upload artifacts
         uses: actions/upload-artifact@v4
         with:
           name: skytemple-windows-app-x64
           path: |
-            installer/skytemple-*-install-*.exe
+            installer/skytemple-*.exe
 
   package-mac:
     runs-on: macos-12
@@ -320,20 +340,24 @@ jobs:
           . .yq-venv/bin/activate
           pip install yq
           echo "PACKAGE_VERSION=$(tomlq '.project.version' pyproject.toml -r)" >> $GITHUB_ENV
-      - name: Install and package
+      - name: Install base packages
         run: |
-          # git is already installed.
-          brew install enchant pygobject3 gtk+3 python@3.11 gtksourceview4 adwaita-icon-theme sdl12-compat sdl2 cmake
+          brew install enchant pygobject3 gtk+3 python@3.12 gtksourceview4 adwaita-icon-theme sdl12-compat sdl2 cmake
+          echo "PATH=/usr/local/opt/python@3.12/bin:/usr/local/bin:$PATH" >> $GITHUB_ENV
           
-          python3.11 -m venv .venv
+          python3.12 -m venv .venv
           . .venv/bin/activate
           pip3 debug --verbose  # print compatible tags etc. for debugging purposes
-          
-          pip3 install -U certifi
 
-
+      - name: Make sure PyGObject is available.
+        run: |
+          . .venv/bin/activate
+          pip3 install "pygobject>=3.44.0"
+      - name: Install and package
+        run: |
+          . .venv/bin/activate
           # Install other dependencies and SkyTemple itself
-          pip3 install py-desmume 'pyinstaller~=5.0'
+          pip3 install skytemple-rust 'pyinstaller~=6.0'
           if [ -n "$IS_DEV_BUILD" ]; then
             IS_MACOS=1 installer/install-skytemple-rust.sh x86_64
           fi
@@ -344,14 +368,11 @@ jobs:
           if [ -n "$IS_DEV_BUILD" ]; then
             installer/install-skytemple-components-from-git.sh
           fi
+          
+          # Check GObject availability
+          python -c 'import gi; gi.require_version("Gtk", "3.0"); from gi.repository import GObject, Gio, GLib, Gtk, Gdk'
 
           cd installer
-
-          # Install themes
-          curl https://skytemple.org/build_deps/Arc.zip -O
-          unzip Arc.zip > /dev/null
-          curl https://skytemple.org/build_deps/ZorinBlue.zip -O
-          unzip ZorinBlue.zip > /dev/null
 
           # Download armips
           curl https://skytemple.org/build_deps/mac/armips -O
@@ -367,7 +388,7 @@ jobs:
           brew install graphicsmagick imagemagick
 
           # This tool returns exit code 2 if the DMG was created but code signing failed for some reason
-          npx create-dmg --dmg-title=SkyTemple installer/dist/SkyTemple.app installer || true
+          npx create-dmg --dmg-title="SkyTemple" "installer/dist/SkyTemple.app" installer || true
 
       - name: Upload .dmg
         uses: actions/upload-artifact@v4
@@ -375,4 +396,79 @@ jobs:
           name: skytemple-mac-dmg-x86_64
           path: |
             installer/SkyTemple*.dmg
-  
+
+  package-mac-arm64:
+    runs-on: macos-14
+    name: Build and package for Mac OS (ARM)
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          submodules: true
+      - name: Rewrite version for dev if not tag
+        if: "!startsWith(github.ref, 'refs/tags/')"
+        run: |
+          perl -i -pe "s/version\s*=\s*\"(.*?)(\.rc.*|\.a.*|\.post.*)?\"/version=\"\1.dev0+${GITHUB_SHA::8}\"/" pyproject.toml
+          echo "IS_DEV_BUILD=1" >> $GITHUB_ENV
+      - name: Note version
+        run: |
+          python3 -m venv .yq-venv
+          . .yq-venv/bin/activate
+          pip install yq
+          echo "PACKAGE_VERSION=$(tomlq '.project.version' pyproject.toml -r)" >> $GITHUB_ENV
+      - name: Install base packages
+        run: |
+          brew install enchant pygobject3 gtk+3 python@3.12 gtksourceview4 adwaita-icon-theme sdl12-compat sdl2 cmake
+          echo "PATH=/usr/local/opt/python@3.12/bin:/usr/local/bin:$PATH" >> $GITHUB_ENV
+          
+          python3.12 -m venv .venv
+          . .venv/bin/activate
+          pip3 debug --verbose  # print compatible tags etc. for debugging purposes
+
+      - name: Make sure PyGObject is available.
+        run: |
+          . .venv/bin/activate
+          pip3 install "pygobject>=3.44.0"
+      - name: Install and package
+        run: |
+          . .venv/bin/activate
+          # Install other dependencies and SkyTemple itself
+          pip3 install skytemple-rust 'pyinstaller~=6.0'
+          if [ -n "$IS_DEV_BUILD" ]; then
+            IS_MACOS=1 installer/install-skytemple-rust.sh x86_64
+          fi
+          pip3 install -r requirements-mac-windows.txt
+          # Generate MO localization files
+          installer/generate-mo.sh
+          pip3 install '.[eventserver]'
+          if [ -n "$IS_DEV_BUILD" ]; then
+            installer/install-skytemple-components-from-git.sh
+          fi
+          
+          # Check GObject availability
+          python -c 'import gi; gi.require_version("Gtk", "3.0"); from gi.repository import GObject, Gio, GLib, Gtk, Gdk'
+
+          cd installer
+
+          # Download armips
+          curl https://skytemple.org/build_deps/mac/armips-mac-arm64 -o armips
+          chmod +x armips
+
+          # Package
+          ./build-mac.sh $PACKAGE_VERSION
+
+      - name: Create installer
+        run: |
+          # See https://github.com/sindresorhus/create-dmg
+          # create-dmg automatically generates an installer icon if imagemagick is installed
+          brew install graphicsmagick imagemagick
+
+          # This tool returns exit code 2 if the DMG was created but code signing failed for some reason
+          npx create-dmg --dmg-title="SkyTemple" "installer/dist/SkyTemple.app" installer || true
+
+      - name: Upload .dmg
+        uses: actions/upload-artifact@v4
+        with:
+          name: skytemple-mac-dmg-arm64
+          path: |
+            installer/SkyTemple*.dmg
