Migrate settings from Randomizer in preperation for GTK4

diff --git a/.github/workflows/build-test-publish.yml b/.github/workflows/build-test-publish.yml
--- a/.github/workflows/build-test-publish.yml
+++ b/.github/workflows/build-test-publish.yml
@@ -6,7 +6,6 @@ on:
   push:
     branches:
       - master
-      - l10n_master
       - release
       - version/*
   pull_request:
@@ -49,7 +48,7 @@ jobs:
         python -m pip install --upgrade pip
         pip install -r requirements.txt ruff
     - name: Lint with ruff
-      run: ruff check --output-format=github .
+      run: ruff check --output-format=github skytemple
 
   code-formatting:
     runs-on: ubuntu-latest
@@ -65,15 +64,19 @@ jobs:
           python -m pip install --upgrade pip
           pip install ruff
       - name: Check with ruff
-        run: ruff format --check .
-        
+        run: ruff format --check skytemple
+
   build:
     runs-on: ubuntu-latest
     name: Build the Python wheel
+    container:
+      image: ghcr.io/skytemple/gtk4-build-image:1
     steps:
       # For tags we assume the version in pyproject.toml is correct!
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          submodules: true
       - name: Rewrite version for dev if not tag
         if: "!startsWith(github.ref, 'refs/tags/')"
         run: |
@@ -81,14 +84,12 @@ jobs:
       - name: Note version
         run: |
           echo "PACKAGE_VERSION=$(tomlq '.project.version' pyproject.toml -r)" >> $GITHUB_ENV
-      - name: Build localization MO files
-        run: |
-          installer/generate-mo.sh
+      - name: Run make
+        run: make
       - name: Build Python wheels
-        uses: RalfG/python-wheels-manylinux-build@v0.5.0-manylinux2014_x86_64
-        with:
-          python-versions: 'cp39-cp39 cp310-cp310 cp311-cp311 cp312-cp312'
-          system-packages: 'gettext'
+        run: |
+          python3 -m pip install --upgrade build
+          python3 -m build
       - name: Upload wheels
         uses: actions/upload-artifact@v4
         with:
@@ -100,6 +101,7 @@ jobs:
       - build
       - package-windows
       - package-mac
+      - package-mac-arm64
     runs-on: ubuntu-latest
     name: Deploy wheels to PyPI
     steps:
@@ -218,6 +220,8 @@ jobs:
             win-gtk-build-2024-5-0-1
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          submodules: true
       # Temporarily move the preinstalled git, it causes errors related to cygwin.
       - name: Move git binary
         run: |
@@ -248,7 +252,7 @@ jobs:
         run: |
           $env:path = "C:\pipx_bin;" + $env:path
           
-          gvsbuild build --fast-build --ninja-opts -j2 --enable-gi --py-wheel gtk3 pygobject openssl gettext gtksourceview4 hicolor-icon-theme adwaita-icon-theme
+          gvsbuild build --fast-build --ninja-opts -j2 --enable-gi --py-wheel gtk4 pygobject openssl gettext gtksourceview5 libadwaita hicolor-icon-theme adwaita-icon-theme
       - name: Restore git binary
         run: |
           Move-Item "C:\Program Files\Git\usr\notbin" "C:\Program Files\Git\usr\bin"
@@ -270,38 +274,45 @@ jobs:
         run: |
           $ErrorActionPreference = "Stop"
 
+          $env:pathext = $env:pathext + ";.PY"
           $env:path = "C:\gtk-build\gtk\x64\release\bin;" + $env:path
           $env:LIB = "C:\gtk-build\gtk\x64\release\lib;" + $env:LIB
           $env:INCLUDE = "C:\gtk-build\gtk\x64\release\include;C:\gtk-build\gtk\x64\release\include\cairo;C:\gtk-build\gtk\x64\release\include\glib-2.0;C:\gtk-build\gtk\x64\release\include\gobject-introspection-1.0;C:\gtk-build\gtk\x64\release\lib\glib-2.0\include;" + $env:INCLUDE
 
-          cd installer
+          # Install PyGObject and pycairo
+          pip install --force-reinstall (Resolve-Path C:\gtk-build\build\x64\release\pygobject\dist\PyGObject*.whl)
+          pip install --force-reinstall (Resolve-Path C:\gtk-build\build\x64\release\pycairo\dist\pycairo*.whl)
           
-          pip debug --verbose  # print compatible tags etc. for debugging purposes
+          # Check GObject availability
+          python -c 'import gi; gi.require_version("Gtk", "4.0"); gi.require_version("Adw", "1"); from gi.repository import GObject, Gio, GLib, Gtk, Gdk, Adw'
+          if ($LASTEXITCODE) { exit $LASTEXITCODE }
+          
+          # Convert Blueprint files
+          .\build-blp-to-ui.ps1
+          if ($LASTEXITCODE) { exit $LASTEXITCODE }
+
+          cd installer
 
           # Package
           .\build-windows.ps1 $PACKAGE_VERSION
+          if ($LASTEXITCODE) { exit $LASTEXITCODE }
 
-          
           if(!(Test-Path ".\dist\skytemple\skytemple.exe")){
-              return 1
+              exit 1
           }
-          
-          # Install latest skytemple-rust
-          if ($env:IS_DEV_BUILD) {
-              bash .\install-skytemple-rust.sh
-          }
+
       - name: Create installer
-        uses: joncloud/makensis-action@v3.7
+        uses: joncloud/makensis-action@v4.1
         with:
           script-file: "installer/skytemple.nsi"
-          arguments: "/DPRODUCT_VERSION=${{ env.PACKAGE_VERSION }}"
+          arguments: "/DPRODUCT_VERSION=${{ env.PACKAGE_VERSION }} /DINST_LIST=install_list.nsh /DUNINST_LIST=uninstall_list.nsh"
 
       - name: Upload artifacts
         uses: actions/upload-artifact@v4
         with:
           name: skytemple-windows-app-x64
           path: |
-            installer/skytemple-*-install-*.exe
+            installer/skytemple-*.exe
 
   package-mac:
     runs-on: macos-12
@@ -309,6 +320,8 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          submodules: true
       - name: Rewrite version for dev if not tag
         if: "!startsWith(github.ref, 'refs/tags/')"
         run: |
@@ -320,20 +333,28 @@ jobs:
           . .yq-venv/bin/activate
           pip install yq
           echo "PACKAGE_VERSION=$(tomlq '.project.version' pyproject.toml -r)" >> $GITHUB_ENV
-      - name: Install and package
+      - name: Install base packages
         run: |
-          # git is already installed.
-          brew install enchant pygobject3 gtk+3 python@3.11 gtksourceview4 adwaita-icon-theme sdl12-compat sdl2 cmake
+          brew install pygobject3 gtk4 python@3.12 gtksourceview5 libadwaita adwaita-icon-theme sdl cmake
+          echo "PATH=/usr/local/opt/python@3.12/bin:/usr/local/bin:$PATH" >> $GITHUB_ENV
           
-          python3.11 -m venv .venv
+          python3.12 -m venv .venv
           . .venv/bin/activate
           pip3 debug --verbose  # print compatible tags etc. for debugging purposes
-          
-          pip3 install -U certifi
 
-
+      - name: Make sure PyGObject is available.
+        run: |
+          . .venv/bin/activate
+          pip3 install "pygobject>=3.44.0"
+      - name: Convert Blueprint files
+        run: |
+          . .venv/bin/activate
+          ./build-blp-to-ui.sh
+      - name: Install and package
+        run: |
+          . .venv/bin/activate
           # Install other dependencies and SkyTemple itself
-          pip3 install py-desmume 'pyinstaller~=5.0'
+          pip3 install skytemple-rust 'pyinstaller~=6.0'
           if [ -n "$IS_DEV_BUILD" ]; then
             IS_MACOS=1 installer/install-skytemple-rust.sh x86_64
           fi
@@ -344,14 +365,11 @@ jobs:
           if [ -n "$IS_DEV_BUILD" ]; then
             installer/install-skytemple-components-from-git.sh
           fi
+          
+          # Check GObject availability
+          python -c 'import gi; gi.require_version("Gtk", "4.0"); gi.require_version("Adw", "1"); from gi.repository import GObject, Gio, GLib, Gtk, Gdk, Adw'
 
           cd installer
-
-          # Install themes
-          curl https://skytemple.org/build_deps/Arc.zip -O
-          unzip Arc.zip > /dev/null
-          curl https://skytemple.org/build_deps/ZorinBlue.zip -O
-          unzip ZorinBlue.zip > /dev/null
 
           # Download armips
           curl https://skytemple.org/build_deps/mac/armips -O
@@ -360,27 +378,14 @@ jobs:
           # Package
           ./build-mac.sh $PACKAGE_VERSION
 
-          # Creating a zip makes the artifact upload much faster since there are so many files
-          zip -r skytemple-mac.zip dist/SkyTemple.app > /dev/null
-
-      - name: Upload .app
-        uses: actions/upload-artifact@v4
-        with:
-          name: skytemple-mac-app-x86_64
-          path: |
-            installer/skytemple-mac.zip
-
       - name: Create installer
         run: |
-          PATH=/usr/local/opt/python@3.11/bin:/usr/local/bin:$PATH
-          
           # See https://github.com/sindresorhus/create-dmg
           # create-dmg automatically generates an installer icon if imagemagick is installed
           brew install graphicsmagick imagemagick
-          npm -g install create-dmg
 
           # This tool returns exit code 2 if the DMG was created but code signing failed for some reason
-          npx create-dmg --dmg-title=SkyTemple installer/dist/SkyTemple.app installer || true
+          npx create-dmg --dmg-title="SkyTemple" "installer/dist/SkyTemple.app" installer || true
 
       - name: Upload .dmg
         uses: actions/upload-artifact@v4
@@ -388,4 +393,83 @@ jobs:
           name: skytemple-mac-dmg-x86_64
           path: |
             installer/SkyTemple*.dmg
-  
+
+  package-mac-arm64:
+    runs-on: macos-14
+    name: Build and package for Mac OS (ARM)
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          submodules: true
+      - name: Rewrite version for dev if not tag
+        if: "!startsWith(github.ref, 'refs/tags/')"
+        run: |
+          perl -i -pe "s/version\s*=\s*\"(.*?)(\.rc.*|\.a.*|\.post.*)?\"/version=\"\1.dev0+${GITHUB_SHA::8}\"/" pyproject.toml
+          echo "IS_DEV_BUILD=1" >> $GITHUB_ENV
+      - name: Note version
+        run: |
+          python3 -m venv .yq-venv
+          . .yq-venv/bin/activate
+          pip install yq
+          echo "PACKAGE_VERSION=$(tomlq '.project.version' pyproject.toml -r)" >> $GITHUB_ENV
+      - name: Install base packages
+        run: |
+          brew install pygobject3 gtk4 python@3.12 gtksourceview5 libadwaita adwaita-icon-theme sdl meson cmake
+          echo "PATH=/usr/local/opt/python@3.12/bin:/usr/local/bin:$PATH" >> $GITHUB_ENV
+          
+          python3.12 -m venv .venv
+          . .venv/bin/activate
+          pip3 debug --verbose  # print compatible tags etc. for debugging purposes
+
+      - name: Make sure PyGObject is available.
+        run: |
+          . .venv/bin/activate
+          pip3 install "pygobject>=3.44.0"
+      - name: Convert Blueprint files
+        run: |
+          . .venv/bin/activate
+          ./build-blp-to-ui.sh
+      - name: Install and package
+        run: |
+          . .venv/bin/activate
+          # Install other dependencies and SkyTemple itself
+          pip3 install skytemple-rust 'pyinstaller~=6.0'
+          if [ -n "$IS_DEV_BUILD" ]; then
+            IS_MACOS=1 installer/install-skytemple-rust.sh x86_64
+          fi
+          pip3 install -r requirements-mac-windows.txt
+          # Generate MO localization files
+          installer/generate-mo.sh
+          pip3 install '.[eventserver]'
+          if [ -n "$IS_DEV_BUILD" ]; then
+            installer/install-skytemple-components-from-git.sh
+          fi
+          
+          # Check GObject availability
+          python -c 'import gi; gi.require_version("Gtk", "4.0"); gi.require_version("Adw", "1"); from gi.repository import GObject, Gio, GLib, Gtk, Gdk, Adw'
+
+          cd installer
+
+          # Download armips
+          curl https://skytemple.org/build_deps/mac/armips-mac-arm64 -o armips
+          chmod +x armips
+
+          # Package
+          ./build-mac.sh $PACKAGE_VERSION
+
+      - name: Create installer
+        run: |
+          # See https://github.com/sindresorhus/create-dmg
+          # create-dmg automatically generates an installer icon if imagemagick is installed
+          brew install graphicsmagick imagemagick
+
+          # This tool returns exit code 2 if the DMG was created but code signing failed for some reason
+          npx create-dmg --dmg-title="SkyTemple" "installer/dist/SkyTemple.app" installer || true
+
+      - name: Upload .dmg
+        uses: actions/upload-artifact@v4
+        with:
+          name: skytemple-mac-dmg-arm64
+          path: |
+            installer/SkyTemple*.dmg
